server:
  port: 8888
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat
    uri-encoding: UTF-8
    # default 200
    max-threads: 500
    min-spare-threads: 10
    max-connections: 10000
  error:
    path: /error
    include-exception: false
    include-stacktrace: ALWAYS
    whitelabel:
      enabled: true
  servlet:
    session:
      timeout: 60m
    application-display-name: evaluation
    #context-path: /eva

spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
    url: jdbc:mysql://localhost:3306/yczhbsdt?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    sql-script-encoding: UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-test-query: select 1 from dual
      connection-timeout: 10000
      pool-name: main_mysql_datasource

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:  classpath:/mapping/*/*.xml
  type-aliases-package: cn.luckyray.evaluation.entity
#开启swagger2
swagger2:
  enable: true
