server:
  port: 8888
  tomcat:
    accesslog:
      enabled: true
    basedir: target/tomcat
    uri-encoding: UTF-8
    # default 200
    max-threads: 500
    min-spare-threads: 10
    max-connections: 10000
  error:
    path: /error
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: true
  servlet:
    session:
      timeout: 60m
    application-display-name: evaluation

spring:
  http.encoding.force: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    sql-script-encoding: UTF-8

  jpa:
    show-sql: true
    open-in-view: false
#showSql
logging:
  level:
    cn:
      luckyray:
        evaluation:
          mapper : info

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:  classpath:/mapping/*.xml
  type-aliases-package: cn.luckyray.evaluation.entity